#!/bin/sh
# Enable WLAN by default on Realtek legacy boards.
# Do not overwrite SSID, encryption, channel, or radio-specific settings.
if [ -x /sbin/uci ]; then
	for radio in $(uci show wireless 2>/dev/null | sed -n 's/^wireless\.\(@wifi-device\[[0-9][0-9]*\]\)\.disabled=.*/\1/p' | sort -u); do
		uci set wireless.$radio.disabled='0'
	done
	for iface in $(uci show wireless 2>/dev/null | sed -n 's/^wireless\.\(@wifi-iface\[[0-9][0-9]*\]\)\.disabled=.*/\1/p' | sort -u); do
		uci set wireless.$iface.disabled='0'
	done
	uci commit wireless
fi

exit 0
