#!/bin/sh
# Bring both Realtek radios up on first boot with an open AP.
[ -x /sbin/wifi ] || exit 0
uci -q set wireless.radio0.disabled='0'
uci -q set wireless.radio1.disabled='0'
uci -q set wireless.default_radio0.encryption='none'
uci -q set wireless.default_radio1.encryption='none'
uci -q set wireless.default_radio0.key=''
uci -q set wireless.default_radio1.key=''
uci -q commit wireless
/sbin/wifi up
exit 0
